import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center py-2">
      <Head>
        <title>Home - Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    LEt's build netflix

    {/* Header */}

    <main>
      {/* Banner */}
      <section>
        {/* Row */}
        {/* Row */}
        {/* Row */}
        {/* Row */}
      </section>
    </main>

    {/* Modal */}
    </div>
  )
}

export default Home
